name: CI
env:
  ACTION_CACHE_PATH: |
    ~/.cargo/bin/
    ~/.cargo/registry/index/
    ~/.cargo/registry/cache/
    ~/.cargo/git/db/
    target/
permissions:
  contents: write
  id-token: write
on:
  push:
    paths:
      - crates/**
      - packages/**
      - tests/**
      - Cargo.lock
    branches:
      - master
  pull_request:
    paths:
      - crates/**
      - packages/**
      - tests/**
      - Cargo.lock
    branches:
      - master
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  publish:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable
      - uses: actions/cache@v6
        with:
          path: ${{ env.ACTION_CACHE_PATH }}
          key: build
      - run: cargo build
